### ISSUE TITLE
Progress Bar infinite property doesn't work

### ISSUE THREAD

**Issue by KlonD90** [NilFoundation/ui-kit#112]
Progress Bar infinite don't move at all. It's just don't do anything now. It should have some animation without proper expectation how long it should be.

Component current state https://nilfoundation.github.io/ui-kit/?path=/story/feedback-progress-bar--small&args=infinite:true
Progress bar in Figma https://www.figma.com/file/FLMXt93XK69cKJYxxftZXD/%3Dnil%3B-Foundation-ui-kit?type=design&node-id=22208-260710&mode=design&t=IB8gYhVmjFC4udcV-0

**Comment by ukorvl** [comment]
New [ProgressBar](https://www.figma.com/file/YjE625ScDMf2ILjWB1sTMc/System?type=design&node-id=789-15622&mode=design&t=QXSxMZjpuXREgul7-0)

**Comment by ukorvl** [comment]
New ProgressBar is redundant. We just need to add infinite animation to the existing one.
