### ISSUE TITLE
Create Toggle buttons group components

### ISSUE THREAD

**Issue by ukorvl** [NilFoundation/ui-kit#171]
### Motivation
We want to have component to implement toggle groups, for example for tags in the blog:
<img width="397" alt="Screen Shot 2023-10-19 at 11 57 42" src="https://github.com/NilFoundation/ui-kit/assets/71327746/228c5a66-2673-4cd5-b8ec-594d7b3333be">

Toggle button in different states:
<img width="397" alt="Screen Shot 2023-10-19 at 10 35 47" src="https://github.com/NilFoundation/ui-kit/assets/71327746/d52efa00-cd25-4f82-a80d-abc370957278">

### Formalization
We should add new `kind=TOGGLE` to the [Button](https://github.com/NilFoundation/ui-kit/blob/master/src/components/button/Button.tsx) component. Kind `TOGGLE`:
- applies styles from the screenshot to button.
- adds default `role="switch"` attribute (but can be overridden)
- adds `checked` attribute
- adds `aria-checked` attribute

**ToggleButtonsGroup**
It is flex container, which wraps items if necessary. Buttons group control buttons state inside. It accepts ref as well (should use forwardRef)
It uses Button with king `TOGGLE` under the hood.

### API
Props:
- options {{key: string, label: string}} - configuration of items inside container.
- onToggle {({activeKeys}: {activeKeys: string[]}) => void} - callback to run on activeKeys change.
- activeKeys {string[]} - active button keys. Only keys of provided options are allowed.
- disabled {boolean} - disables all buttons inside (optional).
- className {string} - for customization of container (optional).
- label {string} - sets label of the buttons group (optional).
- multiple {boolean} - when true multiply items can be selected, otherwise activeKeys array is supposed to have only one item (optional).

activeKeys should be keys of options (not just strings)

### Accessibility
- tab, shift + tab - to move focus between buttons inside container.
- Space or Enter - to toggle button `active` state
- `aria-selected`, `aria-disabled` are applied to the buttons respectively
- Label has id, which is referenced in toggle buttons container via `aria-labelledby`

### Usage example:
```tsx
import {ToggleButtonsGroup} from '@nilfoundation/ui-kit';
// Basic usage
const [activeKeys, setActiveKeys] = useState(['proof-market']);
return (
  <ToggleButtonsGroup
    options={[{key: 'proof-market', label: 'Proof Market'}]}
    activeKeys={activeKeys}
    onToggle={({ activeKeys }) => {
      setActiveKeys(activeKeys);
    }}
  />
);
```
---
```tsx
import {Button} from '@nilfoundation/ui-kit';
//...
return (
  <Button
    kind={BUTTON_KIND.TOGGLE}
    checked={true}
  />
);
```

**Comment by KlonD90** [comment]
ToggleButton should have active as props. It will be better if we want it style somehow or need it as single styled element not in connection with group.

ToggleButtonsGroup better have an API that will receive a list of options as parameters. It will be better for control. Why it's better from my point of view. In this case you manipulate of component by Context and something like it and give idea that i could write something here like an additional styling or something like that.

Also it should have one work with api without changing it depends on multiple. Like `activeKeys={['key']}` in all cases and multiple could be handle by the same api and singular work something like handler for onChange just slice last arguments like `onChange={(keys) => setActiveKeys(keys.slice(-1))}` like that.

**Comment by ukorvl** [comment]
1. It should never be used outside the group, because it violates accessibility. Button should not be used for toggling something, it should be a switch component. To prevent that probably even better use Compound components. If we want one button - use group with 1 option.
2. Ok, changed.
3. Fair enough. Changed.
